"use client";

import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import { Button } from "./button";
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "./drawer";

const meta = {
  title: "UI/Drawer",
  tags: ["autodocs"],
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (
    <Drawer>
      <DrawerTrigger asChild>
        <Button size="sm">Open activity drawer</Button>
      </DrawerTrigger>
      <DrawerContent>
        <DrawerHeader>
          <DrawerTitle>Document activity</DrawerTitle>
          <DrawerDescription>Review recent access, exports, and signature events for this file.</DrawerDescription>
        </DrawerHeader>
        <div className="space-y-3 text-sm">
          {activityItems.map((item) => (
            <div key={item.title} className="rounded-lg border border-border/70 bg-muted/[0.25] p-3">
              <div className="font-medium text-foreground">{item.title}</div>
              <div className="mt-1 text-muted-foreground">{item.description}</div>
            </div>
          ))}
        </div>
        <DrawerFooter>
          <DrawerClose asChild>
            <Button variant="outline" size="sm">
              Close
            </Button>
          </DrawerClose>
          <Button size="sm">View audit log</Button>
        </DrawerFooter>
      </DrawerContent>
    </Drawer>
  ),
};

export const Sides: Story = {
  render: () => (
    <div className="flex flex-wrap gap-3">
      {drawerSides.map((side) => (
        <Drawer key={side}>
          <DrawerTrigger asChild>
            <Button variant="outline" size="sm" className="capitalize">
              {side}
            </Button>
          </DrawerTrigger>
          <DrawerContent side={side}>
            <DrawerHeader>
              <DrawerTitle className="capitalize">{side} drawer</DrawerTitle>
              <DrawerDescription>Drawers can enter from any viewport edge.</DrawerDescription>
            </DrawerHeader>
            <p className="text-sm text-muted-foreground">
              Use this pattern for supplemental workflows that should not replace the current page.
            </p>
          </DrawerContent>
        </Drawer>
      ))}
    </div>
  ),
};

const drawerSides = ["top", "right", "bottom", "left"] as const;

const activityItems = [
  {
    title: "Shared with external counsel",
    description: "Access expires in 7 days unless the workspace policy changes.",
  },
  {
    title: "Watermarked export created",
    description: "Generated by Compliance Admin with IP and timestamp overlays.",
  },
  {
    title: "Signature packet prepared",
    description: "Three reviewers were assigned before the legal hold cutoff.",
  },
];
